---
name: CI
on: push
jobs:
  build:
    strategy:
        matrix:
          cc: [ g++, clang++ ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: ./.github/actions/ghaction-cmake
        with:
          cxx: ${{ matrix.cc }}
  clang-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: DoozyX/clang-format-lint-action@v0.5
  clang-analyzers:
    strategy:
        matrix:
          analyzer: [ clang-tidy, iwyu, cppcheck ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: ./.github/actions/ghaction-cmake
        with:
          analyzer: ${{ matrix.analyzer }}
  omnilint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: docker://lpenz/omnilint:latest
