---
name: CI
on: push
jobs:
  build:
    strategy:
        matrix:
          cc: [ g++, clang++ ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: ./.github/actions/ghaction-cmake
        with:
          cxx: ${{ matrix.cc }}
  envtest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: ./.github/actions/ghaction-cmake
        with:
          env: "[ 'CXX': 'clang++' ]"
  clang-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: DoozyX/clang-format-lint-action@v0.5
  presets:
    strategy:
        matrix:
          preset: 
            - clang-tidy
            - iwyu
            - cppcheck
            - clang-sanitize-address
            - clang-sanitize-memory
            - clang-sanitize-undefined
            - clang-sanitize-dataflow
            - clang-sanitize-safe-stack
            - valgrind
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: ./.github/actions/ghaction-cmake
        with:
          preset: ${{ matrix.preset }}
  omnilint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: docker://lpenz/omnilint:latest
